// <auto-generated />
using System;
using ECommerce.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Infrastructure.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECommerce.Core.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e8f7e8f3-da48-c0d1-968e-818366c73e95"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Intelligent Concrete Tuna",
                            Price = 84579740.12m,
                            Quantity = 412
                        },
                        new
                        {
                            Id = new Guid("3b8b3c1f-132d-1faa-53ba-4d756c1d16fe"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Ergonomic Wooden Gloves",
                            Price = 76596374.90m,
                            Quantity = 828
                        },
                        new
                        {
                            Id = new Guid("f8f0197d-3673-4917-a74d-c12251064620"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Generic Soft Bacon",
                            Price = 19566652.27m,
                            Quantity = 791
                        },
                        new
                        {
                            Id = new Guid("51a59cbe-c551-4c4f-f733-679517ec7afe"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Handmade Steel Salad",
                            Price = 26069353.86m,
                            Quantity = 519
                        },
                        new
                        {
                            Id = new Guid("86cbc59d-12fe-5e37-e927-6fab9a1e6cef"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Licensed Concrete Tuna",
                            Price = 69801296.89m,
                            Quantity = 47
                        },
                        new
                        {
                            Id = new Guid("5721ccd8-3b66-3ce4-53e0-8dced86307fb"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Ergonomic Steel Gloves",
                            Price = 12374293.60m,
                            Quantity = 310
                        },
                        new
                        {
                            Id = new Guid("abe35886-f954-c8fb-5084-9f8fea05ff6d"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Practical Rubber Towels",
                            Price = 82688238.74m,
                            Quantity = 658
                        },
                        new
                        {
                            Id = new Guid("7fdaf6f0-b6d6-9e8b-1886-3ddafbd0405a"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Sleek Cotton Tuna",
                            Price = 12325608.19m,
                            Quantity = 693
                        },
                        new
                        {
                            Id = new Guid("32b260fd-1b56-069d-6a71-0d8ce053e108"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Gorgeous Soft Pizza",
                            Price = 64073239.62m,
                            Quantity = 451
                        },
                        new
                        {
                            Id = new Guid("c74064ec-8524-28f4-b1e0-ade60a9aa7cd"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Ergonomic Wooden Salad",
                            Price = 65565596.61m,
                            Quantity = 525
                        },
                        new
                        {
                            Id = new Guid("3456d017-22b2-99d3-1e5e-9fd6b8eff6d4"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Sleek Metal Chair",
                            Price = 35122156.88m,
                            Quantity = 567
                        },
                        new
                        {
                            Id = new Guid("5fa6addf-9a06-6684-a51d-379c29ed78bb"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Licensed Wooden Hat",
                            Price = 50946712.65m,
                            Quantity = 765
                        },
                        new
                        {
                            Id = new Guid("458b526e-7265-f943-0477-6127d4fccb43"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Generic Metal Car",
                            Price = 18497679.85m,
                            Quantity = 650
                        },
                        new
                        {
                            Id = new Guid("cc07e57e-a3e8-db92-f373-bef8439b1b54"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Refined Rubber Chair",
                            Price = 9457636.08m,
                            Quantity = 228
                        },
                        new
                        {
                            Id = new Guid("5355d9e8-2ecf-92b1-4c1c-4d56933d560e"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Incredible Fresh Car",
                            Price = 71770222.94m,
                            Quantity = 699
                        },
                        new
                        {
                            Id = new Guid("9af2c74d-518a-6b51-afa6-d7c6e2f73c93"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Refined Fresh Chicken",
                            Price = 32189457.12m,
                            Quantity = 578
                        },
                        new
                        {
                            Id = new Guid("2bdfb177-4f56-7274-ee16-7fa71e11547e"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Ergonomic Concrete Ball",
                            Price = 58164526.86m,
                            Quantity = 529
                        },
                        new
                        {
                            Id = new Guid("080885ec-790b-2835-6bbe-4be4142e9f44"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Tasty Cotton Computer",
                            Price = 791126.03m,
                            Quantity = 880
                        },
                        new
                        {
                            Id = new Guid("236d8492-9a3e-c99c-10b7-757ff6ceaf8d"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Ergonomic Steel Table",
                            Price = 7267973.88m,
                            Quantity = 241
                        },
                        new
                        {
                            Id = new Guid("691959e4-7f49-d53a-eed3-7136d03e0f3e"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Tasty Steel Table",
                            Price = 39587738.54m,
                            Quantity = 584
                        },
                        new
                        {
                            Id = new Guid("8a18a2af-137c-c7a0-294b-2123fc9b43bf"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Practical Frozen Pants",
                            Price = 20949044.28m,
                            Quantity = 993
                        },
                        new
                        {
                            Id = new Guid("00c99a40-6bbd-f899-bc5b-7b005b08e017"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Rustic Concrete Cheese",
                            Price = 39609036.36m,
                            Quantity = 373
                        },
                        new
                        {
                            Id = new Guid("be34b643-416f-33d8-39a3-5ee1f4994b56"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Handcrafted Steel Shirt",
                            Price = 76921267.52m,
                            Quantity = 211
                        },
                        new
                        {
                            Id = new Guid("757385e1-b81c-e44b-acd5-1b3e8a02f616"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Generic Granite Shirt",
                            Price = 7131967.28m,
                            Quantity = 190
                        },
                        new
                        {
                            Id = new Guid("9ded06ae-160d-2e12-91be-d550ee7cf69d"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Small Fresh Pizza",
                            Price = 84402623.08m,
                            Quantity = 318
                        },
                        new
                        {
                            Id = new Guid("afc2d383-e637-e91d-a3ec-8abd2e535947"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Licensed Frozen Chair",
                            Price = 33829771.35m,
                            Quantity = 414
                        },
                        new
                        {
                            Id = new Guid("99861843-ea7d-5a2a-0604-46e54568c959"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "The Football Is Good For Training And Recreational Purposes",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Practical Steel Keyboard",
                            Price = 55111638.36m,
                            Quantity = 609
                        },
                        new
                        {
                            Id = new Guid("2bd14ac0-9123-86c2-7cd4-01ffd16e7f87"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Practical Steel Hat",
                            Price = 64901760.32m,
                            Quantity = 499
                        },
                        new
                        {
                            Id = new Guid("d85c5b40-e866-fb9c-3390-55d2008ad91e"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Refined Metal Pizza",
                            Price = 25203299.14m,
                            Quantity = 867
                        },
                        new
                        {
                            Id = new Guid("d0bc6aba-7c05-00ff-80eb-a7ff922fb491"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Ergonomic Rubber Car",
                            Price = 50297627.05m,
                            Quantity = 720
                        },
                        new
                        {
                            Id = new Guid("266afa84-ee75-3bb7-475f-d10aeb9f33dd"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Handcrafted Soft Towels",
                            Price = 4177539.04m,
                            Quantity = 938
                        },
                        new
                        {
                            Id = new Guid("81ff1f1d-fe4c-02b0-995b-00f3470b763f"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Awesome Steel Salad",
                            Price = 17870919.98m,
                            Quantity = 910
                        },
                        new
                        {
                            Id = new Guid("6722545a-1d3e-1cbe-6c90-a55dc8fc4a87"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Generic Granite Car",
                            Price = 76832273.58m,
                            Quantity = 350
                        },
                        new
                        {
                            Id = new Guid("73af70fc-b0ba-a737-e124-2ff7c7f51b70"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Gorgeous Granite Computer",
                            Price = 64370004.69m,
                            Quantity = 169
                        },
                        new
                        {
                            Id = new Guid("789b21ef-c05f-ac26-f750-bbcfaa984216"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Intelligent Cotton Gloves",
                            Price = 80064696.52m,
                            Quantity = 161
                        },
                        new
                        {
                            Id = new Guid("54fe3498-7c0e-0e75-012d-8a25e0f15f15"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Rustic Fresh Bike",
                            Price = 69293217.13m,
                            Quantity = 980
                        },
                        new
                        {
                            Id = new Guid("b77e1041-2639-c3cc-7f83-073d91b4ec5f"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "The Nagasaki Lander is the trademarked name of several series of Nagasaki sport bikes, that started with the 1984 ABC800J",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Handmade Frozen Cheese",
                            Price = 52526675.68m,
                            Quantity = 801
                        },
                        new
                        {
                            Id = new Guid("f4f35595-8f46-51b8-0ffb-d28594eb312d"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Awesome Wooden Shirt",
                            Price = 74730505.83m,
                            Quantity = 269
                        },
                        new
                        {
                            Id = new Guid("69f29cd9-10e4-943d-d991-63913aa404d1"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Small Concrete Computer",
                            Price = 27749490.81m,
                            Quantity = 859
                        },
                        new
                        {
                            Id = new Guid("aa4686af-c76f-d1a1-6c0e-6b4b2045e01a"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Handcrafted Metal Bacon",
                            Price = 32424393.39m,
                            Quantity = 189
                        },
                        new
                        {
                            Id = new Guid("8ec218bb-e4cf-1ec3-b5c8-4640f9f732e6"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Handcrafted Steel Pants",
                            Price = 45844593.11m,
                            Quantity = 833
                        },
                        new
                        {
                            Id = new Guid("11be85d4-69cd-36ff-b3e8-4f271d80743a"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Rustic Wooden Bike",
                            Price = 89660143.86m,
                            Quantity = 99
                        },
                        new
                        {
                            Id = new Guid("c1449f5c-b1cd-d4b9-2e70-3364c8abed7e"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Unbranded Fresh Bike",
                            Price = 42156867.91m,
                            Quantity = 143
                        },
                        new
                        {
                            Id = new Guid("1f83baa3-32d3-5856-7cc5-e4a09a2d6ff7"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Ergonomic Granite Fish",
                            Price = 12477667.37m,
                            Quantity = 400
                        },
                        new
                        {
                            Id = new Guid("7f365142-b71b-e5ea-3e45-fc177250f6fd"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "The slim & simple Maple Gaming Keyboard from Dev Byte comes with a sleek body and 7- Color RGB LED Back-lighting for smart functionality",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Tasty Frozen Bacon",
                            Price = 63125304.15m,
                            Quantity = 173
                        },
                        new
                        {
                            Id = new Guid("9661d782-7551-f6e6-3265-236fb6fde9c5"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "New range of formal shirts are designed keeping you in mind. With fits and styling that will make you stand apart",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Generic Steel Chicken",
                            Price = 40621086.84m,
                            Quantity = 229
                        },
                        new
                        {
                            Id = new Guid("20374180-968d-15dc-8ab0-86967f8b9a5b"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "The Apollotech B340 is an affordable wireless mouse with reliable connectivity, 12 months battery life and modern design",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Incredible Concrete Towels",
                            Price = 55219948.21m,
                            Quantity = 445
                        },
                        new
                        {
                            Id = new Guid("c0fff77d-3bae-c2ef-1488-29d72b24be5e"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "Boston's most advanced compression wear technology increases muscle oxygenation, stabilizes active muscles",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Fantastic Rubber Keyboard",
                            Price = 84289005.51m,
                            Quantity = 907
                        },
                        new
                        {
                            Id = new Guid("56262b86-9f0a-6bbf-a776-1a78a72576cb"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "Carbonite web goalkeeper gloves are ergonomically designed to give easy fit",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Small Rubber Car",
                            Price = 84539829.06m,
                            Quantity = 703
                        },
                        new
                        {
                            Id = new Guid("033b9314-1c59-43c6-0ae6-54638591fdb6"),
                            CreatedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Description = "New ABC 13 9370, 13.3, 5th Gen CoreA5-8250U, 8GB RAM, 256GB SSD, power UHD Graphics, OS 10 Home, OS Office A & J 2016",
                            ModifiedDate = new DateTime(2024, 4, 18, 11, 48, 14, 27, DateTimeKind.Local).AddTicks(5696),
                            Name = "Small Plastic Chair",
                            Price = 16539026.55m,
                            Quantity = 542
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
